### ISSUE TITLE
Can't join LAN server

### ISSUE THREAD

**Issue by Zadnicaff** [Lolcroc/ProjectLepton#17]
**Forge version**: 39.0.10 1.18.1
**Mod version**: 1.2.2

When I try to join LAN server with no other mods I get this:
![error](https://user-images.githubusercontent.com/20302928/148333326-9e8f01ff-135a-4fc9-939a-50c9b681c3ff.png)

**Comment by mont-40** [comment]
I'm not sure if this is related to my mod. Can you post a link to your `latest.log` in the logs directory directly after you reproduce this error?

**Comment by Zadnicaff** [comment]
Sure:
[latest.log](https://github.com/Lolcroc/CraftingAutomat/files/7833369/latest.log)

**Comment by mont-40** [comment]
The log looks clean. I have tried to recreate your error with 2 local clients on a bare install of Forge + Crafting Automat. However I can connect through LAN just fine. Have you tried hosting on the other client?

There are some recent discussions on Reddit that suspect this is a problem native to Forge. I have found [this solution](https://www.reddit.com/r/CreateMod/comments/rxph6h/comment/hrmlm7o/?utm_source=share&utm_medium=web2x&context=3), could you try it?

**Comment by Zadnicaff** [comment]
Hosting on the other client and setting the network on both machines to private didn't work.

I've also tried this with Create and Flywheel mods and it gave me the same error, so it looks like this isn't only specific to your mod.

The best solution I could find is to run a separate server instead of the ingame "Open to LAN" option.

**Comment by dragon3025** [comment]
I'm having the same problem, when only this mod is installed. My sister gets kicked right after joining when I host a LAN server. I tried setting both connections to private, but it didn't work.
Forge: 1.18.1-forge-39.0.14 (I also tried it with 39.0.5 previously)
My latest log: [latest.log](https://github.com/Lolcroc/CraftingAutomat/files/7835898/latest.log)

Since this could be a forge issue: I created an issue for it here: https://github.com/MinecraftForge/MinecraftForge/issues/8377

**Comment by mont-40** [comment]
This issue was non-existent pre-Caves and Cliffs. I don't know why Forge devs claim this problem is "not them", as it's clearly already affecting multiple mods. There is some networking in Crafting Automat that I can try to disable (through config), but it means you'll have to test the result yourself. I'll give you an update later

**Comment by RavenFayrin** [comment]
My friend and I tested everything we had running and it was the Create mod causing the problem. Every other time I tried to connect with this mod or that, or just with Forge it worked fine. It was when we added Create that it refused.

**Comment by dragon3025** [comment]
> My friend and I tested everything we had running and it was the Create mod causing the problem. Every other time I tried to connect with this mod or that, or just with Forge it worked fine. It was when we added Create that it refused.

I had this problem when only Crafting Automat was installed, but there are others having a problem with the create mod also. What ever this is, it seems to be affecting people differently.

**Comment by mont-40** [comment]
@dragon3025 I have made a test version for you [here](https://www.curseforge.com/minecraft/mc-mods/crafting-automat/files/3604617). It's important that the LAN host installs the fix, and sets `syncronizeTickSettings` in their config file to `false`. I assume it's not necessary that other players install the fix, but you could try anyway.

**Comment by dragon3025** [comment]
Thank you, it tested it out and it worked.
