### ISSUE TITLE
mode suggestion: crafting for auto build system.

### ISSUE THREAD

**Issue by korg** [Lolcroc/ProjectLepton#24]
Im trying to use craftingautomat to build a factory, with something smart delivering resources to build and then pulling out the results as needed (with one automat per recipe).

So image there was a 'crafting node mode button' that did something like the following...

  1) only accepted enough resources to build the recipe once (eg, 1 coal, 1 stick for torches or 8 planks for a crafting block)

  2) builds immediately without a redstone signal when it has all ingredients (*and* it has an empty output slot)

  3) stops building after that one item and holds it internally for something outside to pull out (eg, refined storage or laserio)

  4) repeat

Only accepts ingredient input (to the limit of the number needed to make 1 item) and only outputs the generated result. So an inserter is limited in the type and number of items in and an exporter can only grab the result item.

One suggestion would be to add a 10th slot to that inventory that only the automat can put items in and to have that hold the crafting result (or for that 10th square to be the existing output box the grid points to)

The other suggestion would be to 'borrow' the idea from automated-crafting and have a recipe grid that the player sets, an inventory grid that the feeding machine can fill and an extraction box/grid that the automat puts the result in (and that hoppers/extractors can pull from).

I note that i cant pull resources out of the square that the recipe/grid points to (although i can manually grab them), but i can machine extract them from the inventory bar below that. So in the torch example id currently have to set the extractor to filter torches only (not that i could get laser io to be an acceptor for the automat as it just spit them out) but it would be nice to just have any sort of exporting pipe only be able to pull out the generated item, not the input ingredients.

**Comment by mont-40** [comment]
Hello. I feel like you're overthinking your factory; Minecraft already gives you quite some tools for automation. The majority of your problem may be fixed by putting a "buffer" inventory in front of the automat, and pulling items from that, rather than directly from the automat. This inventory acts exactly like the extraction box/grid you describe, except that it is a separate block.

For your other problem; this is how I would do it. Put a comparator on the buffer inventory, and hook the output to the hoppers feeding the automat (or whatever other mechanism, there's usually a way to modulate item flow with redstone). The result is a buffer inventory that fills up with crafted items, and stops whenever you don't pull them out. Just make sure you have a redstone clock hooked on the automat so that it may craft whenever it has the ingredients.
